Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.1563.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'FBTXBatchFoodItemsCustomUIModel' data form
''' </summary>
Partial Public Class [FBTXBatchFoodItemsCustomUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _fooditems As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchFoodItemsCustomFOODITEMSUIModel)

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public Sub New()
        MyBase.New()

        _fooditems = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchFoodItemsCustomFOODITEMSUIModel)

        MyBase.FORMHEADER.Value = "Food Items"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FBTXBatchFoodItemsCustomUIModel.html"

        '
        '_fooditems
        '
        _fooditems.Name = "FOODITEMS"
        _fooditems.Caption = "Food Items"
        Me.Fields.Add(_fooditems)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Food Items
    ''' </summary>
    <System.ComponentModel.Description("Food Items")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [FOODITEMS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchFoodItemsCustomFOODITEMSUIModel)
        Get
            Return _fooditems
        End Get
    End Property
    
End Class
