'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
'
Namespace SpellCheckSvc
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="checkSoap", [Namespace]:="http://ws.cdyne.com/")>  _
    Partial Public Class check
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private CheckTextBodyV2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private CheckTextBodyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Blackbaud.CustomFx.FoodBank.Client.My.MySettings.Default.Blackbaud_CustomFx_FoodBank_Client_SpellCheckSvc_check
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event CheckTextBodyV2Completed As CheckTextBodyV2CompletedEventHandler
        
        '''<remarks/>
        Public Event CheckTextBodyCompleted As CheckTextBodyCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.cdyne.com/CheckTextBodyV2", RequestNamespace:="http://ws.cdyne.com/", ResponseNamespace:="http://ws.cdyne.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckTextBodyV2(ByVal BodyText As String) As <System.Xml.Serialization.XmlElementAttribute("DocumentSummary", IsNullable:=true)> DocumentSummary
            Dim results() As Object = Me.Invoke("CheckTextBodyV2", New Object() {BodyText})
            Return CType(results(0),DocumentSummary)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckTextBodyV2Async(ByVal BodyText As String)
            Me.CheckTextBodyV2Async(BodyText, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckTextBodyV2Async(ByVal BodyText As String, ByVal userState As Object)
            If (Me.CheckTextBodyV2OperationCompleted Is Nothing) Then
                Me.CheckTextBodyV2OperationCompleted = AddressOf Me.OnCheckTextBodyV2OperationCompleted
            End If
            Me.InvokeAsync("CheckTextBodyV2", New Object() {BodyText}, Me.CheckTextBodyV2OperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckTextBodyV2OperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckTextBodyV2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckTextBodyV2Completed(Me, New CheckTextBodyV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.cdyne.com/CheckTextBody", RequestNamespace:="http://ws.cdyne.com/", ResponseNamespace:="http://ws.cdyne.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function CheckTextBody(ByVal BodyText As String, ByVal LicenseKey As String) As <System.Xml.Serialization.XmlElementAttribute("DocumentSummary", IsNullable:=true)> DocumentSummary
            Dim results() As Object = Me.Invoke("CheckTextBody", New Object() {BodyText, LicenseKey})
            Return CType(results(0),DocumentSummary)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CheckTextBodyAsync(ByVal BodyText As String, ByVal LicenseKey As String)
            Me.CheckTextBodyAsync(BodyText, LicenseKey, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CheckTextBodyAsync(ByVal BodyText As String, ByVal LicenseKey As String, ByVal userState As Object)
            If (Me.CheckTextBodyOperationCompleted Is Nothing) Then
                Me.CheckTextBodyOperationCompleted = AddressOf Me.OnCheckTextBodyOperationCompleted
            End If
            Me.InvokeAsync("CheckTextBody", New Object() {BodyText, LicenseKey}, Me.CheckTextBodyOperationCompleted, userState)
        End Sub
        
        Private Sub OnCheckTextBodyOperationCompleted(ByVal arg As Object)
            If (Not (Me.CheckTextBodyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CheckTextBodyCompleted(Me, New CheckTextBodyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.cdyne.com/")>  _
    Partial Public Class DocumentSummary
        
        Private misspelledWordField() As Words
        
        Private verField As String
        
        Private bodyField As String
        
        Private misspelledWordCountField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MisspelledWord")>  _
        Public Property MisspelledWord() As Words()
            Get
                Return Me.misspelledWordField
            End Get
            Set
                Me.misspelledWordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ver() As String
            Get
                Return Me.verField
            End Get
            Set
                Me.verField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property body() As String
            Get
                Return Me.bodyField
            End Get
            Set
                Me.bodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MisspelledWordCount() As Integer
            Get
                Return Me.misspelledWordCountField
            End Get
            Set
                Me.misspelledWordCountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.cdyne.com/")>  _
    Partial Public Class Words
        
        Private suggestionsField() As String
        
        Private wordField As String
        
        Private suggestionCountField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Suggestions")>  _
        Public Property Suggestions() As String()
            Get
                Return Me.suggestionsField
            End Get
            Set
                Me.suggestionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property word() As String
            Get
                Return Me.wordField
            End Get
            Set
                Me.wordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SuggestionCount() As Integer
            Get
                Return Me.suggestionCountField
            End Get
            Set
                Me.suggestionCountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub CheckTextBodyV2CompletedEventHandler(ByVal sender As Object, ByVal e As CheckTextBodyV2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckTextBodyV2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentSummary
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentSummary)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub CheckTextBodyCompletedEventHandler(ByVal sender As Object, ByVal e As CheckTextBodyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CheckTextBodyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As DocumentSummary
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),DocumentSummary)
            End Get
        End Property
    End Class
End Namespace
