Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Sustained Giving Dashboard Parameters View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "f9240de4-1e56-4baf-b620-6552d10b6379", "d26508bf-789f-43b8-aff6-91517a2ae507", "")>
Partial Public Class [SustainedGivingParametersViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the DATETYPE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum DATETYPES As Integer
        [SpecificDate] = 0
        [AllDates] = 1
        [ThisYear] = 7
        [LastYear] = 13
        [LastMonth] = 12
        [ThisMonth] = 6
        [LastQuarter] = 45
        [ThisQuarter] = 43
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _revenueamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _datetype As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _enddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _revenueamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _datetype = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _enddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("f9240de4-1e56-4baf-b620-6552d10b6379")
        MyBase.DataFormInstanceId = New System.Guid("d26508bf-789f-43b8-aff6-91517a2ae507")
        MyBase.RecordType = ""
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.openfx.reporting/SustainedGivingParametersViewDataForm.html"

        '
        '_revenueamount
        '
        _revenueamount.Name = "REVENUEAMOUNT"
        _revenueamount.Caption = "Revenue Amount"
        _revenueamount.DBReadOnly = True
        Me.Fields.Add(_revenueamount)
        '
        '_datetype
        '
        _datetype.Name = "DATETYPE"
        _datetype.Caption = "Date"
        _datetype.Required = True
        _datetype.DBReadOnly = True
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[SpecificDate], .Translation = "Specific Date"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[AllDates], .Translation = "All Dates"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisYear], .Translation = "This Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastYear], .Translation = "Last Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastMonth], .Translation = "Last Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisMonth], .Translation = "This Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastQuarter], .Translation = "Last Quarter"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisQuarter], .Translation = "This Quarter"})
        _datetype.Value = DATETYPES.[AllDates]
        Me.Fields.Add(_datetype)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Start date"
        _startdate.DBReadOnly = True
        Me.Fields.Add(_startdate)
        '
        '_enddate
        '
        _enddate.Name = "ENDDATE"
        _enddate.Caption = "End date"
        _enddate.DBReadOnly = True
        Me.Fields.Add(_enddate)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Revenue Amount
    ''' </summary>
    <System.ComponentModel.Description("Revenue Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [REVENUEAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _revenueamount
        End Get
    End Property
    
    ''' <summary>
    ''' Date
    ''' </summary>
    <System.ComponentModel.Description("Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATETYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        Get
            Return _datetype
        End Get
    End Property
    
    ''' <summary>
    ''' Start date
    ''' </summary>
    <System.ComponentModel.Description("Start date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' End date
    ''' </summary>
    <System.ComponentModel.Description("End date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _enddate
        End Get
    End Property
    
End Class
