Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Sustained Giving Summary View Data Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "0ba66482-4e54-4f27-9d95-f41c16d9a24e", "8a8ee963-080b-4036-80cb-674f604e7efa", "")>
Partial Public Class [SustainedGivingSummaryViewDataFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _activedonors As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _totalrevenue As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _newdonors As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _lostdonors As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _enddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _activedonors = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _totalrevenue = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _newdonors = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _lostdonors = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _enddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New System.Guid("0ba66482-4e54-4f27-9d95-f41c16d9a24e")
        MyBase.DataFormInstanceId = New System.Guid("8a8ee963-080b-4036-80cb-674f604e7efa")
        MyBase.RecordType = ""
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.openfx.reporting/SustainedGivingSummaryViewDataForm.html"

        '
        '_activedonors
        '
        _activedonors.Name = "ACTIVEDONORS"
        _activedonors.Caption = "Active donors"
        _activedonors.DBReadOnly = True
        Me.Fields.Add(_activedonors)
        '
        '_totalrevenue
        '
        _totalrevenue.Name = "TOTALREVENUE"
        _totalrevenue.Caption = "Total revenue"
        _totalrevenue.DBReadOnly = True
        Me.Fields.Add(_totalrevenue)
        '
        '_newdonors
        '
        _newdonors.Name = "NEWDONORS"
        _newdonors.Caption = "New donors"
        _newdonors.DBReadOnly = True
        Me.Fields.Add(_newdonors)
        '
        '_lostdonors
        '
        _lostdonors.Name = "LOSTDONORS"
        _lostdonors.Caption = "Lost donors"
        _lostdonors.DBReadOnly = True
        Me.Fields.Add(_lostdonors)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Start date"
        _startdate.DBReadOnly = True
        Me.Fields.Add(_startdate)
        '
        '_enddate
        '
        _enddate.Name = "ENDDATE"
        _enddate.Caption = "End date"
        _enddate.DBReadOnly = True
        Me.Fields.Add(_enddate)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Active donors
    ''' </summary>
    <System.ComponentModel.Description("Active donors")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ACTIVEDONORS]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _activedonors
        End Get
    End Property
    
    ''' <summary>
    ''' Total revenue
    ''' </summary>
    <System.ComponentModel.Description("Total revenue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [TOTALREVENUE]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _totalrevenue
        End Get
    End Property
    
    ''' <summary>
    ''' New donors
    ''' </summary>
    <System.ComponentModel.Description("New donors")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [NEWDONORS]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _newdonors
        End Get
    End Property
    
    ''' <summary>
    ''' Lost donors
    ''' </summary>
    <System.ComponentModel.Description("Lost donors")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [LOSTDONORS]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _lostdonors
        End Get
    End Property
    
    ''' <summary>
    ''' Start date
    ''' </summary>
    <System.ComponentModel.Description("Start date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' End date
    ''' </summary>
    <System.ComponentModel.Description("End date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _enddate
        End Get
    End Property
    
End Class
