Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Top Donors Report' data form
''' </summary>

Partial Public Class [TopDonorsReportUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.ReportParameterUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the MAXROWS property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum MAXROWSValues As Integer
        [_10] = 10
        [_50] = 50
        [_100] = 100
    End Enum

    ''' <summary>
    ''' Enumerated values for use with the DATETYPE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum DATETYPES As Integer
        [SpecificDate] = 0
        [AllDates] = 1
        [ThisYear] = 7
        [LastYear] = 13
        [LastMonth] = 12
        [ThisMonth] = 6
        [LastQuarter] = 45
        [ThisQuarter] = 43
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _maxrows As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of MAXROWSValues))
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _enddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _datetype As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
    Private WithEvents _showadvancedfilters As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _includenotposted As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _includeanonymous As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _includepledges As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _basicfilterstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _advancedfilterstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _maxrows = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of MAXROWSValues))
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _enddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _datetype = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        _showadvancedfilters = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _includenotposted = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _includeanonymous = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _includepledges = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _basicfilterstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _advancedfilterstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField

        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.openfx.reporting/TopDonorsReport.html"

        '
        '_maxrows
        '
        _maxrows.Name = "MAXROWS"
        _maxrows.Caption = "Include top "
        _maxrows.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of MAXROWSValues)) With {.Value = MAXROWSValues.[_10], .Translation = "10"})
        _maxrows.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of MAXROWSValues)) With {.Value = MAXROWSValues.[_50], .Translation = "50"})
        _maxrows.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of MAXROWSValues)) With {.Value = MAXROWSValues.[_100], .Translation = "100"})
        _maxrows.Value = MAXROWSValues.[_50]
        Me.Fields.Add(_maxrows)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Start Date"
        Me.Fields.Add(_startdate)
        '
        '_enddate
        '
        _enddate.Name = "ENDDATE"
        _enddate.Caption = "End Date"
        Me.Fields.Add(_enddate)
        '
        '_datetype
        '
        _datetype.Name = "DATETYPE"
        _datetype.Caption = "Date"
        _datetype.Required = True
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[SpecificDate], .Translation = "Specific Date"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[AllDates], .Translation = "All Dates"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisYear], .Translation = "This Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastYear], .Translation = "Last Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastMonth], .Translation = "Last Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisMonth], .Translation = "This Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastQuarter], .Translation = "Last Quarter"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisQuarter], .Translation = "This Quarter"})
        _datetype.Value = DATETYPES.[AllDates]
        Me.Fields.Add(_datetype)
        '
        '_showadvancedfilters
        '
        _showadvancedfilters.Name = "SHOWADVANCEDFILTERS"
        _showadvancedfilters.Caption = "Show advanced filters"
        Me.Fields.Add(_showadvancedfilters)
        '
        '_includenotposted
        '
        _includenotposted.Name = "INCLUDENOTPOSTED"
        _includenotposted.Caption = "Include not posted revenue"
        Me.Fields.Add(_includenotposted)
        '
        '_includeanonymous
        '
        _includeanonymous.Name = "INCLUDEANONYMOUS"
        _includeanonymous.Caption = "Include anonymous revenue"
        Me.Fields.Add(_includeanonymous)
        '
        '_includepledges
        '
        _includepledges.Name = "INCLUDEPLEDGES"
        _includepledges.Caption = "Include pledges"
        Me.Fields.Add(_includepledges)
        '
        '_basicfilterstab
        '
        _basicfilterstab.Name = "BASICFILTERSTAB"
        _basicfilterstab.Caption = "Filters"
        Me.Fields.Add(_basicfilterstab)
        '
        '_advancedfilterstab
        '
        _advancedfilterstab.Name = "ADVANCEDFILTERSTAB"
        _advancedfilterstab.Caption = "Advanced filters"
        Me.Fields.Add(_advancedfilterstab)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Include top 
    ''' </summary>
    <System.ComponentModel.Description("Include top ")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [MAXROWS]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of MAXROWSValues))
        Get
            Return _maxrows
        End Get
    End Property
    
    ''' <summary>
    ''' Start Date
    ''' </summary>
    <System.ComponentModel.Description("Start Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' End Date
    ''' </summary>
    <System.ComponentModel.Description("End Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _enddate
        End Get
    End Property
    
    ''' <summary>
    ''' Date
    ''' </summary>
    <System.ComponentModel.Description("Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATETYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        Get
            Return _datetype
        End Get
    End Property
    
    ''' <summary>
    ''' Show advanced filters
    ''' </summary>
    <System.ComponentModel.Description("Show advanced filters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [SHOWADVANCEDFILTERS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _showadvancedfilters
        End Get
    End Property
    
    ''' <summary>
    ''' Include not posted revenue
    ''' </summary>
    <System.ComponentModel.Description("Include not posted revenue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [INCLUDENOTPOSTED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _includenotposted
        End Get
    End Property
    
    ''' <summary>
    ''' Include anonymous revenue
    ''' </summary>
    <System.ComponentModel.Description("Include anonymous revenue")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [INCLUDEANONYMOUS]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _includeanonymous
        End Get
    End Property
    
    ''' <summary>
    ''' Include pledges
    ''' </summary>
    <System.ComponentModel.Description("Include pledges")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [INCLUDEPLEDGES]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _includepledges
        End Get
    End Property
    
    ''' <summary>
    ''' Filters
    ''' </summary>
    <System.ComponentModel.Description("Filters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [BASICFILTERSTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _basicfilterstab
        End Get
    End Property
    
    ''' <summary>
    ''' Advanced filters
    ''' </summary>
    <System.ComponentModel.Description("Advanced filters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ADVANCEDFILTERSTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _advancedfilterstab
        End Get
    End Property
    
End Class
