Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.1563.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'FBTXBatchReconcileCustomFOODITEMS' data form
''' </summary>
Partial Public Class [FBTXBatchReconcileCustomFOODITEMSUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _foodbankname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _batchtxfooditemname As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentprodinv As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _batchtxinv As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _potentialreconciledprodinv As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public Sub New()
        MyBase.New()

        _foodbankname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _batchtxfooditemname = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentprodinv = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _batchtxinv = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _potentialreconciledprodinv = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField

        '
        '_foodbankname
        '
        _foodbankname.Name = "FOODBANKNAME"
        _foodbankname.Caption = "Food Bank"
        _foodbankname.Visible = False
        _foodbankname.DBReadOnly = True
        Me.Fields.Add(_foodbankname)
        '
        '_batchtxfooditemname
        '
        _batchtxfooditemname.Name = "BATCHTXFOODITEMNAME"
        _batchtxfooditemname.Caption = "Food Item"
        _batchtxfooditemname.DBReadOnly = True
        _batchtxfooditemname.MaxLength = 100

        Me.Fields.Add(_batchtxfooditemname)
        '
        '_currentprodinv
        '
        _currentprodinv.Name = "CURRENTPRODINV"
        _currentprodinv.Caption = "Actual"
        _currentprodinv.DBReadOnly = True
        Me.Fields.Add(_currentprodinv)
        '
        '_batchtxinv
        '
        _batchtxinv.Name = "BATCHTXINV"
        _batchtxinv.Caption = "Batch Adjustment"
        Me.Fields.Add(_batchtxinv)
        '
        '_potentialreconciledprodinv
        '
        _potentialreconciledprodinv.Name = "POTENTIALRECONCILEDPRODINV"
        _potentialreconciledprodinv.Caption = "Adjusted Actual"
        _potentialreconciledprodinv.DBReadOnly = True
        Me.Fields.Add(_potentialreconciledprodinv)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Food Bank
    ''' </summary>
    <System.ComponentModel.Description("Food Bank")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [FOODBANKNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _foodbankname
        End Get
    End Property

    ''' <summary>
    ''' Food Item
    ''' </summary>
    <System.ComponentModel.Description("Food Item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [BATCHTXFOODITEMNAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _batchtxfooditemname
        End Get
    End Property

    ''' <summary>
    ''' Actual
    ''' </summary>
    <System.ComponentModel.Description("Actual")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [CURRENTPRODINV]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _currentprodinv
        End Get
    End Property
    
    ''' <summary>
    ''' Batch Adjustment
    ''' </summary>
    <System.ComponentModel.Description("Batch Adjustment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [BATCHTXINV]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _batchtxinv
        End Get
    End Property
    
    ''' <summary>
    ''' Adjusted Actual
    ''' </summary>
    <System.ComponentModel.Description("Adjusted Actual")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [POTENTIALRECONCILEDPRODINV]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _potentialreconciledprodinv
        End Get
    End Property
    
End Class
