Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.1563.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'FBTXBatchVsCurInvReconcileCustomUIModel' data form
''' </summary>
Partial Public Class [FBTXBatchReconcileCustomUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _batchid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _foodbankid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _fooditems As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchReconcileCustomFOODITEMSUIModel)

    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public Sub New()
        MyBase.New()

        _batchid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _foodbankid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _fooditems = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchReconcileCustomFOODITEMSUIModel)

        MyBase.FORMHEADER.Value = "Batch Versus Current Inventory Impact"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FBTXBatchVsCurInvReconcileCustomUIModel.html"

        '
        '_batchid
        '
        _batchid.Name = "BATCHID"
        _batchid.Caption = "Batch ID"
        _batchid.Visible = False
        Me.Fields.Add(_batchid)
        '
        '_foodbankid
        '
        _foodbankid.Name = "FOODBANKID"
        _foodbankid.Caption = "Food Bank"
        _foodbankid.SimpleDataListID = New Guid("a8736d9e-912b-4b87-97b4-d53a01984e5c")
        _foodbankid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("BATCHTXCONTEXTID", "Fields!BATCHID"))
        Me.Fields.Add(_foodbankid)
        '
        '_fooditems
        '
        _fooditems.Name = "FOODITEMS"
        _fooditems.Caption = "Food Items"
        Me.Fields.Add(_fooditems)

        OnCreated()

    End Sub

    ''' <summary>
    ''' Batch ID
    ''' </summary>
    <System.ComponentModel.Description("Batch ID")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [BATCHID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _batchid
        End Get
    End Property

    ''' <summary>
    ''' Food Bank
    ''' </summary>
    <System.ComponentModel.Description("Food Bank")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [FOODBANKID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _foodbankid
        End Get
    End Property

    ''' <summary>
    ''' Food Items
    ''' </summary>
    <System.ComponentModel.Description("Food Items")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.1563.0")> _
    Public ReadOnly Property [FOODITEMS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FBTXBatchReconcileCustomFOODITEMSUIModel)
        Get
            Return _fooditems
        End Get
    End Property
    
End Class
