Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.5.465.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Item Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "f4986fa8-4e1a-486b-a4e8-84bb7d16c1e6", "6f80152d-4bd4-43fa-9f73-14ab44a90954", "Food Item")> _
Partial Public Class [FoodItemEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _description As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentcost As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _lowinventorythreshold As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _weight As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public Sub New()
        MyBase.New()

        _name = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _description = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentcost = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _lowinventorythreshold = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _weight = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("f4986fa8-4e1a-486b-a4e8-84bb7d16c1e6")
        MyBase.DataFormInstanceId = New Guid("6f80152d-4bd4-43fa-9f73-14ab44a90954")
        MyBase.RecordType = "Food Item"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodItemEditForm.html"

        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "Name"
        _name.Required = True
        _name.MaxLength = 100
        Me.Fields.Add(_name)
        '
        '_description
        '
        _description.Name = "DESCRIPTION"
        _description.Caption = "Description"
        Me.Fields.Add(_description)
        '
        '_currentcost
        '
        _currentcost.Name = "CURRENTCOST"
        _currentcost.Caption = "Currentcost"
        Me.Fields.Add(_currentcost)
        '
        '_lowinventorythreshold
        '
        _lowinventorythreshold.Name = "LOWINVENTORYTHRESHOLD"
        _lowinventorythreshold.Caption = "Low Inventory Threshold"
        Me.Fields.Add(_lowinventorythreshold)
        '
        '_weight
        '
        _weight.Name = "WEIGHT"
        _weight.Caption = "Weight"
        _weight.Description = "The weight of a food item."
        _weight.Precision = 10
        _weight.Scale = 2
        Me.Fields.Add(_weight)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _name
        End Get
    End Property
    
    ''' <summary>
    ''' Description
    ''' </summary>
    <System.ComponentModel.Description("Description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [DESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _description
        End Get
    End Property
    
    ''' <summary>
    ''' Currentcost
    ''' </summary>
    <System.ComponentModel.Description("Currentcost")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [CURRENTCOST]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _currentcost
        End Get
    End Property
    
    ''' <summary>
    ''' Low Inventory Threshold
    ''' </summary>
    <System.ComponentModel.Description("Low Inventory Threshold")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [LOWINVENTORYTHRESHOLD]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _lowinventorythreshold
        End Get
    End Property
    
    ''' <summary>
    ''' The weight of a food item.
    ''' </summary>
    <System.ComponentModel.Description("The weight of a food item.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [WEIGHT]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _weight
        End Get
    End Property
    
End Class
