Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.5.465.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Bank Summary View' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View, "965337a3-9ce2-459f-90ca-61abb9949cd5", "703f99d3-fb38-409f-9843-3a6a1ab13b4c", "Food Bank")> _
Partial Public Class [FoodBankSummaryViewUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _description As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _missionstatement As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _foodbanktype As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _primaryaddress As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _totalfoodreceived As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _totalfooddistributed As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _totalfoodreceivedamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _totalfooddistributedamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _totalfoodreceivedweight As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
    Private WithEvents _totalfooddistributedweight As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
    Private WithEvents _constituentinfofieldgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _statisticsfieldgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _constituenttab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _statisticstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public Sub New()
        MyBase.New()

        _name = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _description = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _missionstatement = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _foodbanktype = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _primaryaddress = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _totalfoodreceived = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _totalfooddistributed = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _totalfoodreceivedamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _totalfooddistributedamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _totalfoodreceivedweight = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        _totalfooddistributedweight = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        _constituentinfofieldgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _statisticsfieldgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _constituenttab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _statisticstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.View
        MyBase.DataFormTemplateId = New Guid("965337a3-9ce2-459f-90ca-61abb9949cd5")
        MyBase.DataFormInstanceId = New Guid("703f99d3-fb38-409f-9843-3a6a1ab13b4c")
        MyBase.RecordType = "Food Bank"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodBankSummaryView.html"

        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "Name"
        _name.DBReadOnly = True
        _name.MaxLength = 100
        Me.Fields.Add(_name)
        '
        '_description
        '
        _description.Name = "DESCRIPTION"
        _description.Caption = "Description"
        _description.DBReadOnly = True
        Me.Fields.Add(_description)
        '
        '_missionstatement
        '
        _missionstatement.Name = "MISSIONSTATEMENT"
        _missionstatement.Caption = "Mission Statement"
        _missionstatement.DBReadOnly = True
        Me.Fields.Add(_missionstatement)
        '
        '_foodbanktype
        '
        _foodbanktype.Name = "FOODBANKTYPE"
        _foodbanktype.Caption = "Food Bank Type"
        _foodbanktype.DBReadOnly = True
        _foodbanktype.MaxLength = 100
        Me.Fields.Add(_foodbanktype)
        '
        '_primaryaddress
        '
        _primaryaddress.Name = "PRIMARYADDRESS"
        _primaryaddress.Caption = "Primary Address"
        _primaryaddress.DBReadOnly = True
        _primaryaddress.MaxLength = 300
        Me.Fields.Add(_primaryaddress)
        '
        '_totalfoodreceived
        '
        _totalfoodreceived.Name = "TOTALFOODRECEIVED"
        _totalfoodreceived.Caption = "Total Food Received"
        _totalfoodreceived.DBReadOnly = True
        Me.Fields.Add(_totalfoodreceived)
        '
        '_totalfooddistributed
        '
        _totalfooddistributed.Name = "TOTALFOODDISTRIBUTED"
        _totalfooddistributed.Caption = "Total Food Distributed"
        _totalfooddistributed.DBReadOnly = True
        Me.Fields.Add(_totalfooddistributed)
        '
        '_totalfoodreceivedamount
        '
        _totalfoodreceivedamount.Name = "TOTALFOODRECEIVEDAMOUNT"
        _totalfoodreceivedamount.Caption = "Total Received Amount"
        _totalfoodreceivedamount.DBReadOnly = True
        Me.Fields.Add(_totalfoodreceivedamount)
        '
        '_totalfooddistributedamount
        '
        _totalfooddistributedamount.Name = "TOTALFOODDISTRIBUTEDAMOUNT"
        _totalfooddistributedamount.Caption = "Total Distributed Amount"
        _totalfooddistributedamount.DBReadOnly = True
        Me.Fields.Add(_totalfooddistributedamount)
        '
        '_totalfoodreceivedweight
        '
        _totalfoodreceivedweight.Name = "TOTALFOODRECEIVEDWEIGHT"
        _totalfoodreceivedweight.Caption = "Total Received Lbs"
        _totalfoodreceivedweight.DBReadOnly = True
        _totalfoodreceivedweight.Precision = 20
        _totalfoodreceivedweight.Scale = 4
        Me.Fields.Add(_totalfoodreceivedweight)
        '
        '_totalfooddistributedweight
        '
        _totalfooddistributedweight.Name = "TOTALFOODDISTRIBUTEDWEIGHT"
        _totalfooddistributedweight.Caption = "Total Distributed Lbs"
        _totalfooddistributedweight.DBReadOnly = True
        _totalfooddistributedweight.Precision = 20
        _totalfooddistributedweight.Scale = 4
        Me.Fields.Add(_totalfooddistributedweight)
        '
        '_constituentinfofieldgroup
        '
        _constituentinfofieldgroup.Name = "CONSTITUENTINFOFIELDGROUP"
        _constituentinfofieldgroup.Caption = "Constituent"
        _constituentinfofieldgroup.Fields.Add("NAME")
        _constituentinfofieldgroup.Fields.Add("PRIMARYADDRESS")
        _constituentinfofieldgroup.Fields.Add("DESCRIPTION")
        _constituentinfofieldgroup.Fields.Add("MISSIONSTATEMENT")
        _constituentinfofieldgroup.Fields.Add("FOODBANKTYPE")
        Me.Fields.Add(_constituentinfofieldgroup)
        '
        '_statisticsfieldgroup
        '
        _statisticsfieldgroup.Name = "STATISTICSFIELDGROUP"
        _statisticsfieldgroup.Caption = "Statistics"
        _statisticsfieldgroup.Fields.Add("TOTALFOODRECEIVED")
        _statisticsfieldgroup.Fields.Add("TOTALFOODDISTRIBUTED")
        _statisticsfieldgroup.Fields.Add("TOTALFOODRECEIVEDAMOUNT")
        _statisticsfieldgroup.Fields.Add("TOTALFOODDISTRIBUTEDAMOUNT")
        _statisticsfieldgroup.Fields.Add("TOTALFOODRECEIVEDWEIGHT")
        _statisticsfieldgroup.Fields.Add("TOTALFOODDISTRIBUTEDWEIGHT")
        Me.Fields.Add(_statisticsfieldgroup)
        '
        '_constituenttab
        '
        _constituenttab.Name = "CONSTITUENTTAB"
        _constituenttab.Caption = "Constituent Info"
        Me.Fields.Add(_constituenttab)
        '
        '_statisticstab
        '
        _statisticstab.Name = "STATISTICSTAB"
        _statisticstab.Caption = "Stats"
        Me.Fields.Add(_statisticstab)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _name
        End Get
    End Property
    
    ''' <summary>
    ''' Description
    ''' </summary>
    <System.ComponentModel.Description("Description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [DESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _description
        End Get
    End Property
    
    ''' <summary>
    ''' Mission Statement
    ''' </summary>
    <System.ComponentModel.Description("Mission Statement")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [MISSIONSTATEMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _missionstatement
        End Get
    End Property
    
    ''' <summary>
    ''' Food Bank Type
    ''' </summary>
    <System.ComponentModel.Description("Food Bank Type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [FOODBANKTYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _foodbanktype
        End Get
    End Property
    
    ''' <summary>
    ''' Primary Address
    ''' </summary>
    <System.ComponentModel.Description("Primary Address")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [PRIMARYADDRESS]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _primaryaddress
        End Get
    End Property
    
    ''' <summary>
    ''' Total Food Received
    ''' </summary>
    <System.ComponentModel.Description("Total Food Received")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODRECEIVED]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _totalfoodreceived
        End Get
    End Property
    
    ''' <summary>
    ''' Total Food Distributed
    ''' </summary>
    <System.ComponentModel.Description("Total Food Distributed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODDISTRIBUTED]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _totalfooddistributed
        End Get
    End Property
    
    ''' <summary>
    ''' Total Received Amount
    ''' </summary>
    <System.ComponentModel.Description("Total Received Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODRECEIVEDAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _totalfoodreceivedamount
        End Get
    End Property
    
    ''' <summary>
    ''' Total Distributed Amount
    ''' </summary>
    <System.ComponentModel.Description("Total Distributed Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODDISTRIBUTEDAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _totalfooddistributedamount
        End Get
    End Property
    
    ''' <summary>
    ''' Total Received Lbs
    ''' </summary>
    <System.ComponentModel.Description("Total Received Lbs")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODRECEIVEDWEIGHT]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _totalfoodreceivedweight
        End Get
    End Property
    
    ''' <summary>
    ''' Total Distributed Lbs
    ''' </summary>
    <System.ComponentModel.Description("Total Distributed Lbs")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [TOTALFOODDISTRIBUTEDWEIGHT]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _totalfooddistributedweight
        End Get
    End Property
    
    ''' <summary>
    ''' Constituent
    ''' </summary>
    <System.ComponentModel.Description("Constituent")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [CONSTITUENTINFOFIELDGROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _constituentinfofieldgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Statistics
    ''' </summary>
    <System.ComponentModel.Description("Statistics")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [STATISTICSFIELDGROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _statisticsfieldgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Constituent Info
    ''' </summary>
    <System.ComponentModel.Description("Constituent Info")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [CONSTITUENTTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _constituenttab
        End Get
    End Property
    
    ''' <summary>
    ''' Stats
    ''' </summary>
    <System.ComponentModel.Description("Stats")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [STATISTICSTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _statisticstab
        End Get
    End Property
    
End Class
