Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.94.1232.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Item Add Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "ee2cb812-cc6b-41c3-8165-59585f04a2ba", "b911e219-42f2-4b64-9f02-d9e2ff899799", "Food Item")> _
Partial Public Class [FoodItemAddFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _description As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _currentcost As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _lowinventorythreshold As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
    Private WithEvents _weight As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
    Private WithEvents _general As Global.Blackbaud.AppFx.UIModeling.Core.GroupField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public Sub New()
        MyBase.New()

        _name = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _description = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _currentcost = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _lowinventorythreshold = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        _weight = New Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        _general = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("ee2cb812-cc6b-41c3-8165-59585f04a2ba")
        MyBase.DataFormInstanceId = New Guid("b911e219-42f2-4b64-9f02-d9e2ff899799")
        MyBase.RecordType = "Food Item"
        MyBase.FixedDialog = True
        MyBase.FORMHEADER.Value = "Add a Food Item"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodItemAddForm.html"

        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "Name"
        _name.Required = True
        _name.MaxLength = 100
        Me.Fields.Add(_name)
        '
        '_description
        '
        _description.Name = "DESCRIPTION"
        _description.Caption = "Description"
        Me.Fields.Add(_description)
        '
        '_currentcost
        '
        _currentcost.Name = "CURRENTCOST"
        _currentcost.Caption = "Current Cost"
        Me.Fields.Add(_currentcost)
        '
        '_lowinventorythreshold
        '
        _lowinventorythreshold.Name = "LOWINVENTORYTHRESHOLD"
        _lowinventorythreshold.Caption = "Low Inventory Threshold"
        Me.Fields.Add(_lowinventorythreshold)
        '
        '_weight
        '
        _weight.Name = "WEIGHT"
        _weight.Caption = "Weight"
        _weight.Description = "The weight of a food item."
        _weight.Precision = 10
        _weight.Scale = 2
        Me.Fields.Add(_weight)
        '
        '_general
        '
        _general.Name = "GENERAL"
        _general.Caption = "General Stuff"
        _general.Fields.Add("NAME")
        _general.Fields.Add("DESCRIPTION")
        Me.Fields.Add(_general)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _name
        End Get
    End Property
    
    ''' <summary>
    ''' Description
    ''' </summary>
    <System.ComponentModel.Description("Description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [DESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _description
        End Get
    End Property
    
    ''' <summary>
    ''' Current Cost
    ''' </summary>
    <System.ComponentModel.Description("Current Cost")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [CURRENTCOST]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _currentcost
        End Get
    End Property
    
    ''' <summary>
    ''' Low Inventory Threshold
    ''' </summary>
    <System.ComponentModel.Description("Low Inventory Threshold")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [LOWINVENTORYTHRESHOLD]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _lowinventorythreshold
        End Get
    End Property
    
    ''' <summary>
    ''' The weight of a food item.
    ''' </summary>
    <System.ComponentModel.Description("The weight of a food item.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [WEIGHT]() As Global.Blackbaud.AppFx.UIModeling.Core.DecimalField
        Get
            Return _weight
        End Get
    End Property
    
    ''' <summary>
    ''' General Stuff
    ''' </summary>
    <System.ComponentModel.Description("General Stuff")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.94.1232.0")> _
    Public ReadOnly Property [GENERAL]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _general
        End Get
    End Property
    
End Class
