Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.5.465.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Item List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("5d4d94df-d0ee-491a-aaf3-4f3ff5a9c2ba")> _
Partial Public Class [FoodItemListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _name As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public Sub New()
        MyBase.New()

        _name = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        MyBase.DataListId = New Guid("5d4d94df-d0ee-491a-aaf3-4f3ff5a9c2ba")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodItemList.html"

        '
        '_name
        '
        _name.Name = "NAME"
        _name.Caption = "Name"
        _name.MaxLength = 100
        Me.Fields.Add(_name)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Name
    ''' </summary>
    <System.ComponentModel.Description("Name")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [NAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _name
        End Get
    End Property
    
End Class
