Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.429.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Bank Transaction Header Add Form 2' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "6817cae4-ef2a-469b-a44b-0f838327d445", "d19db1cd-3933-4bff-8aca-cc96f334cf44", "Food Bank Transaction Header", "Food Bank")> _
Partial Public Class [FoodBankTransactionHeaderAddForm2UIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the FOODBANKTXTYPECODE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public Enum FOODBANKTXTYPECODES As Integer
        [Receive] = 0
        [Distribute] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _constituentid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _foodbanktxtypecode As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FOODBANKTXTYPECODES)
    Private WithEvents _txdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _receiptprinted As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _fooditems As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankTransactionHeaderAddForm2FOODITEMSUIModel)
    Private WithEvents _addfooditemlabel As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _addfooditem As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public Sub New()
        MyBase.New()

        _constituentid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _foodbanktxtypecode = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FOODBANKTXTYPECODES)
        _txdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _receiptprinted = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _fooditems = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankTransactionHeaderAddForm2FOODITEMSUIModel)
        _addfooditemlabel = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _addfooditem = New Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("6817cae4-ef2a-469b-a44b-0f838327d445")
        MyBase.DataFormInstanceId = New Guid("d19db1cd-3933-4bff-8aca-cc96f334cf44")
        MyBase.RecordType = "Food Bank Transaction Header"
        MyBase.ContextRecordType = "Food Bank"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodBankTransactionHeaderAddForm2.html"

        '
        '_constituentid
        '
        _constituentid.Name = "CONSTITUENTID"
        _constituentid.Caption = "Constituent"
        _constituentid.Description = "The food bank either receives food donations from this constituent or distributes food to this constituent."
        _constituentid.Required = True
        _constituentid.SearchListID = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        _constituentid.EnableQuickFind = True
        Me.Fields.Add(_constituentid)
        '
        '_foodbanktxtypecode
        '
        _foodbanktxtypecode.Name = "FOODBANKTXTYPECODE"
        _foodbanktxtypecode.Caption = "Transaction Type"
        _foodbanktxtypecode.Description = "Enter Receive if the food bank is receiving a donation from the constituent.  Enter Distribute if the food bank is distributing food to the constituent in need."
        _foodbanktxtypecode.Required = True
        _foodbanktxtypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FOODBANKTXTYPECODES) With {.Value = FOODBANKTXTYPECODES.[Receive], .Translation = "Receive"})
        _foodbanktxtypecode.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of FOODBANKTXTYPECODES) With {.Value = FOODBANKTXTYPECODES.[Distribute], .Translation = "Distribute"})
        _foodbanktxtypecode.Value = FOODBANKTXTYPECODES.[Receive]
        Me.Fields.Add(_foodbanktxtypecode)
        '
        '_txdate
        '
        _txdate.Name = "TXDATE"
        _txdate.Caption = "Transaction Date"
        _txdate.Required = True
        Me.Fields.Add(_txdate)
        '
        '_receiptprinted
        '
        _receiptprinted.Name = "RECEIPTPRINTED"
        _receiptprinted.Caption = "Receipt Printed"
        Me.Fields.Add(_receiptprinted)
        '
        '_fooditems
        '
        _fooditems.Name = "FOODITEMS"
        _fooditems.Caption = "Food Items"
        Me.Fields.Add(_fooditems)
        '
        '_addfooditemlabel
        '
        _addfooditemlabel.Name = "ADDFOODITEMLABEL"
        _addfooditemlabel.Caption = "Add Food Item"
        _addfooditemlabel.DBReadOnly = True
        Me.Fields.Add(_addfooditemlabel)
        '
        '_addfooditem
        '
        _addfooditem.Name = "ADDFOODITEM"
        _addfooditem.Caption = "+"
        _addfooditem.Description = "Add Food Item"
        _addfooditem.DataFormInstanceId = New Guid("b911e219-42f2-4b64-9f02-d9e2ff899799")
        Me.Actions.Add(_addfooditem)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' The food bank either receives food donations from this constituent or distributes food to this constituent.
    ''' </summary>
    <System.ComponentModel.Description("The food bank either receives food donations from this constituent or distributes food to this constituent.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [CONSTITUENTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _constituentid
        End Get
    End Property
    
    ''' <summary>
    ''' Enter Receive if the food bank is receiving a donation from the constituent.  Enter Distribute if the food bank is distributing food to the constituent in need.
    ''' </summary>
    <System.ComponentModel.Description("Enter Receive if the food bank is receiving a donation from the constituent.  Enter Distribute if the food bank is distributing food to the constituent in need.")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [FOODBANKTXTYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of FOODBANKTXTYPECODES)
        Get
            Return _foodbanktxtypecode
        End Get
    End Property
    
    ''' <summary>
    ''' Transaction Date
    ''' </summary>
    <System.ComponentModel.Description("Transaction Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [TXDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _txdate
        End Get
    End Property
    
    ''' <summary>
    ''' Receipt Printed
    ''' </summary>
    <System.ComponentModel.Description("Receipt Printed")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [RECEIPTPRINTED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _receiptprinted
        End Get
    End Property
    
    ''' <summary>
    ''' Food Items
    ''' </summary>
    <System.ComponentModel.Description("Food Items")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [FOODITEMS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankTransactionHeaderAddForm2FOODITEMSUIModel)
        Get
            Return _fooditems
        End Get
    End Property
    
    ''' <summary>
    ''' Add Food Item
    ''' </summary>
    <System.ComponentModel.Description("Add Food Item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [ADDFOODITEMLABEL]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _addfooditemlabel
        End Get
    End Property
    
    ''' <summary>
    ''' Add Food Item
    ''' </summary>
    <System.ComponentModel.Description("Add Food Item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [ADDFOODITEM]() As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
        Get
            Return _addfooditem
        End Get
    End Property
    
End Class
