Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.429.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Bank Organization Extension Add Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add, "89025448-7cab-430e-8b9a-b057bf4966cb", "735c77b6-bb12-4298-b76d-aa811da97584", "Food Bank", "Constituent")> _
Partial Public Class [FoodBankOrganizationExtensionAddFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _addfoodbank As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _description As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _missionstatement As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _foodbanktypecodeid As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _generalinformationgroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Private WithEvents _othergroup As Global.Blackbaud.AppFx.UIModeling.Core.GroupField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public Sub New()
        MyBase.New()

        _addfoodbank = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _description = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _missionstatement = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _foodbanktypecodeid = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _generalinformationgroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        _othergroup = New Global.Blackbaud.AppFx.UIModeling.Core.GroupField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Add
        MyBase.DataFormTemplateId = New Guid("89025448-7cab-430e-8b9a-b057bf4966cb")
        MyBase.DataFormInstanceId = New Guid("735c77b6-bb12-4298-b76d-aa811da97584")
        MyBase.RecordType = "Food Bank"
        MyBase.ContextRecordType = "Constituent"
        MyBase.FixedDialog = True
        MyBase.ExtensionTabCaption = "Food Bank"
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodBankOrganizationExtensionAddForm.html"

        '
        '_addfoodbank
        '
        _addfoodbank.Name = "ADDFOODBANK"
        _addfoodbank.Caption = "Add Food Bank"
        Me.Fields.Add(_addfoodbank)
        '
        '_description
        '
        _description.Name = "DESCRIPTION"
        _description.Caption = "Description"
        _description.MultiLine = True
        Me.Fields.Add(_description)
        '
        '_missionstatement
        '
        _missionstatement.Name = "MISSIONSTATEMENT"
        _missionstatement.Caption = "Mission Statement"
        _missionstatement.MultiLine = True
        Me.Fields.Add(_missionstatement)
        '
        '_foodbanktypecodeid
        '
        _foodbanktypecodeid.Name = "FOODBANKTYPECODEID"
        _foodbanktypecodeid.Caption = "Food Bank Type"
        _foodbanktypecodeid.CodeTableName = "USR_FOODBANKTYPECODE"
        Me.Fields.Add(_foodbanktypecodeid)
        '
        '_generalinformationgroup
        '
        _generalinformationgroup.Name = "GENERALINFORMATIONGROUP"
        _generalinformationgroup.Caption = "General Information"
        _generalinformationgroup.Fields.Add("ADDFOODBANK")
        _generalinformationgroup.Fields.Add("DESCRIPTION")
        _generalinformationgroup.Fields.Add("MISSIONSTATEMENT")
        Me.Fields.Add(_generalinformationgroup)
        '
        '_othergroup
        '
        _othergroup.Name = "OTHERGROUP"
        _othergroup.Caption = "Other"
        _othergroup.Fields.Add("FOODBANKTYPECODEID")
        Me.Fields.Add(_othergroup)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Add Food Bank
    ''' </summary>
    <System.ComponentModel.Description("Add Food Bank")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [ADDFOODBANK]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _addfoodbank
        End Get
    End Property
    
    ''' <summary>
    ''' Description
    ''' </summary>
    <System.ComponentModel.Description("Description")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [DESCRIPTION]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _description
        End Get
    End Property
    
    ''' <summary>
    ''' Mission Statement
    ''' </summary>
    <System.ComponentModel.Description("Mission Statement")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [MISSIONSTATEMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _missionstatement
        End Get
    End Property
    
    ''' <summary>
    ''' Food Bank Type
    ''' </summary>
    <System.ComponentModel.Description("Food Bank Type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [FOODBANKTYPECODEID]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _foodbanktypecodeid
        End Get
    End Property
    
    ''' <summary>
    ''' General Information
    ''' </summary>
    <System.ComponentModel.Description("General Information")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [GENERALINFORMATIONGROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _generalinformationgroup
        End Get
    End Property
    
    ''' <summary>
    ''' Other
    ''' </summary>
    <System.ComponentModel.Description("Other")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.429.0")> _
    Public ReadOnly Property [OTHERGROUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
        Get
            Return _othergroup
        End Get
    End Property
    
End Class
