Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.5.465.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Bank Transaction Detail Edit Form' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "4fc5bada-2f8f-4b78-863b-993f7a7f434c", "77b9c56d-f414-47c9-a10b-3b4566d9a39d", "Food Bank Transaction Detail")> _
Partial Public Class [FoodBankTransactionDetailEditFormUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataFormUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _fooditemid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _fooditemamount As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _quantity As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public Sub New()
        MyBase.New()

        _fooditemid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _fooditemamount = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _quantity = New Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField

        MyBase.Mode = Global.Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit
        MyBase.DataFormTemplateId = New Guid("4fc5bada-2f8f-4b78-863b-993f7a7f434c")
        MyBase.DataFormInstanceId = New Guid("77b9c56d-f414-47c9-a10b-3b4566d9a39d")
        MyBase.RecordType = "Food Bank Transaction Detail"
        MyBase.FixedDialog = True
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodBankTransactionDetailEditForm.html"

        '
        '_fooditemid
        '
        _fooditemid.Name = "FOODITEMID"
        _fooditemid.Caption = "Food Item"
        _fooditemid.Required = True
        _fooditemid.SearchListID = New Guid("2c247add-e19e-407f-b6c3-8f3bc5216ccd")
        _fooditemid.EnableQuickFind = True
        Me.Fields.Add(_fooditemid)
        '
        '_fooditemamount
        '
        _fooditemamount.Name = "FOODITEMAMOUNT"
        _fooditemamount.Caption = "Food Item Amount"
        Me.Fields.Add(_fooditemamount)
        '
        '_quantity
        '
        _quantity.Name = "QUANTITY"
        _quantity.Caption = "Quantity"
        Me.Fields.Add(_quantity)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Food Item
    ''' </summary>
    <System.ComponentModel.Description("Food Item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [FOODITEMID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _fooditemid
        End Get
    End Property
    
    ''' <summary>
    ''' Food Item Amount
    ''' </summary>
    <System.ComponentModel.Description("Food Item Amount")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [FOODITEMAMOUNT]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _fooditemamount
        End Get
    End Property
    
    ''' <summary>
    ''' Quantity
    ''' </summary>
    <System.ComponentModel.Description("Quantity")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.5.465.0")> _
    Public ReadOnly Property [QUANTITY]() As Global.Blackbaud.AppFx.UIModeling.Core.SmallIntField
        Get
            Return _quantity
        End Get
    End Property
    
End Class
