'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by Blackbaud.AppFx.SDKVSWizards.dll
'     Version:  2.5.465.0
'     Date:  02/18/2010 8:39:22 AM
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public NotInheritable Class PhoneAddAddIn
    Inherits Blackbaud.AppFx.UIModeling.Core.RootModelAddIn(Of Global.Blackbaud.AppFx.Constituent.UIModel.PhoneAddFormUIModel)

    Friend WithEvents MODEL As Global.Blackbaud.AppFx.Constituent.UIModel.PhoneAddFormUIModel
    Friend WithEvents [PHONETYPECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [NUMBER] As Global.Blackbaud.AppFx.UIModeling.Core.PhoneField
    Friend WithEvents [PRIMARY] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [DONOTCALL] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [SPOUSENAME] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [UPDATEMATCHINGSPOUSEPHONE] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ISHOUSEHOLD] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ISHOUSEHOLDMEMBER] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [UPDATEMATCHINGHOUSEHOLDPHONE] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [STARTTIME] As Global.Blackbaud.AppFx.UIModeling.Core.HourMinuteField
    Friend WithEvents [ENDTIME] As Global.Blackbaud.AppFx.UIModeling.Core.HourMinuteField
    Friend WithEvents [INFOSOURCECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [INFOSOURCECOMMENTS] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [COUNTRYID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [STARTDATE] As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Friend WithEvents [DONOTCALLREASONCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [ISCONFIDENTIAL] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [COUNTRYCODES] As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of Blackbaud.AppFx.Constituent.UIModel.PhoneAddFormCOUNTRYCODESUIModel)
    Friend WithEvents [COUNTRYCODE] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [SOURCEINFORMATION] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [FORMHEADER] As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    Public Overrides Sub Init()

        Me.MODEL = Me.HostModel
        Me.[PHONETYPECODEID] = Me.HostModel.[PHONETYPECODEID]
        Me.[NUMBER] = Me.HostModel.[NUMBER]
        Me.[PRIMARY] = Me.HostModel.[PRIMARY]
        Me.[DONOTCALL] = Me.HostModel.[DONOTCALL]
        Me.[SPOUSENAME] = Me.HostModel.[SPOUSENAME]
        Me.[UPDATEMATCHINGSPOUSEPHONE] = Me.HostModel.[UPDATEMATCHINGSPOUSEPHONE]
        Me.[ISHOUSEHOLD] = Me.HostModel.[ISHOUSEHOLD]
        Me.[ISHOUSEHOLDMEMBER] = Me.HostModel.[ISHOUSEHOLDMEMBER]
        Me.[UPDATEMATCHINGHOUSEHOLDPHONE] = Me.HostModel.[UPDATEMATCHINGHOUSEHOLDPHONE]
        Me.[STARTTIME] = Me.HostModel.[STARTTIME]
        Me.[ENDTIME] = Me.HostModel.[ENDTIME]
        Me.[INFOSOURCECODEID] = Me.HostModel.[INFOSOURCECODEID]
        Me.[INFOSOURCECOMMENTS] = Me.HostModel.[INFOSOURCECOMMENTS]
        Me.[COUNTRYID] = Me.HostModel.[COUNTRYID]
        Me.[STARTDATE] = Me.HostModel.[STARTDATE]
        Me.[DONOTCALLREASONCODEID] = Me.HostModel.[DONOTCALLREASONCODEID]
        Me.[ISCONFIDENTIAL] = Me.HostModel.[ISCONFIDENTIAL]
        Me.[COUNTRYCODES] = Me.HostModel.[COUNTRYCODES]
        Me.[COUNTRYCODE] = Me.HostModel.[COUNTRYCODE]
        Me.[SOURCEINFORMATION] = Me.HostModel.[SOURCEINFORMATION]
        Me.[FORMHEADER] = Me.HostModel.[FORMHEADER]

        OnInit()

    End Sub

    Partial Private Sub OnInit()
    End Sub

End Class

