'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by Blackbaud.AppFx.SDKVSWizards.dll
'     Version:  2.5.465.0
'     Date:  03/01/2010 9:54:02 AM
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Partial Public NotInheritable Class RelationshipOrganizationtoIndividualAddForm2AddIn
    Inherits Blackbaud.AppFx.UIModeling.Core.RootModelAddIn(Of Global.Blackbaud.AppFx.Constituent.UIModel.Relationship.RelationshipOrganizationToIndividualAddForm2UIModel)

    Friend WithEvents MODEL As Global.Blackbaud.AppFx.Constituent.UIModel.Relationship.RelationshipOrganizationToIndividualAddForm2UIModel
    Friend WithEvents [CONSTITUENTNAME] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [ORGPRIMARYADDRESSID] As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Friend WithEvents [RECIPROCALCONSTITUENTID] As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Friend WithEvents [RECIPROCALTYPECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [RELATIONSHIPTYPECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [ISCONTACT] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ISPRIMARYCONTACT] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [CONTACTTYPECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [RELATIONSHIPSTARTDATE] As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Friend WithEvents [RELATIONSHIPENDDATE] As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Friend WithEvents [POSITION] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [ISPRIMARYBUSINESS] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ISMATCHINGGIFTRELATIONSHIP] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ADDADDRESS] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [ADDRESSTYPECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [ADDRESSBLOCK] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [CITY] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [STATEID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [POSTCODE] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [COUNTRYID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [DONOTMAIL] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [CART] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [LOT] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [DPC] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [STARTDATE] As Global.Blackbaud.AppFx.UIModeling.Core.MonthDayField
    Friend WithEvents [ENDDATE] As Global.Blackbaud.AppFx.UIModeling.Core.MonthDayField
    Friend WithEvents [PRIMARY] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [SPOUSENAME] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [UPDATEMATCHINGSPOUSEADDRESSES] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [OMITFROMVALIDATION] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [COUNTYCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [CONGRESSIONALDISTRICTCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [STATEHOUSEDISTRICTCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [STATESENATEDISTRICTCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [LOCALPRECINCTCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [INFOSOURCECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [REGIONCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [LASTVALIDATIONATTEMPTDATE] As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Friend WithEvents [VALIDATIONMESSAGE] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [CERTIFICATIONDATA] As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Friend WithEvents [ZIPLOOKUPCOUNTRIES] As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of Blackbaud.AppFx.Constituent.UIModel.Relationship.RelationshipOrganizationToIndividualAddForm2ZIPLOOKUPCOUNTRIESUIModel)
    Friend WithEvents [VALIDATIONCOUNTRIES] As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of Blackbaud.AppFx.Constituent.UIModel.Relationship.RelationshipOrganizationToIndividualAddForm2VALIDATIONCOUNTRIESUIModel)
    Friend WithEvents [DONOTMAILREASONCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [JOBCATEGORYCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [CAREERLEVELCODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [REPLACERELATIONSHIP] As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Friend WithEvents [REPLACEMENTRELATIONSHIPID] As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Friend WithEvents [INFOSOURCECOMMENTS] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [COMMENTS] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [JOBSCHEDULECODEID] As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Friend WithEvents [JOBDEPARTMENT] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [JOBDIVISION] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [CONSTITUENTTYPE] As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Friend WithEvents [CONTACTADDRESSLABEL] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [CONTACTADDRESS] As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Friend WithEvents [RELATIONSHIPGROUP] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [EMPLOYMENTINFOGROUP] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [GENERALGROUP] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [CONTACTGROUP] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [COMMENTSGROUP] As Global.Blackbaud.AppFx.UIModeling.Core.GroupField
    Friend WithEvents [ADDADDRESSACTION] As Global.Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction
    Friend WithEvents [REMOVEADDRESSACTION] As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Friend WithEvents [ADDNEWINDIVIDUAL] As Global.Blackbaud.AppFx.UIModeling.Core.ShowAddFormUIAction
    Friend WithEvents [FORMHEADER] As Global.Blackbaud.AppFx.UIModeling.Core.StringField

    Public Overrides Sub Init()

        Me.MODEL = Me.HostModel
        Me.[CONSTITUENTNAME] = Me.HostModel.[CONSTITUENTNAME]
        Me.[ORGPRIMARYADDRESSID] = Me.HostModel.[ORGPRIMARYADDRESSID]
        Me.[RECIPROCALCONSTITUENTID] = Me.HostModel.[RECIPROCALCONSTITUENTID]
        Me.[RECIPROCALTYPECODEID] = Me.HostModel.[RECIPROCALTYPECODEID]
        Me.[RELATIONSHIPTYPECODEID] = Me.HostModel.[RELATIONSHIPTYPECODEID]
        Me.[ISCONTACT] = Me.HostModel.[ISCONTACT]
        Me.[ISPRIMARYCONTACT] = Me.HostModel.[ISPRIMARYCONTACT]
        Me.[CONTACTTYPECODEID] = Me.HostModel.[CONTACTTYPECODEID]
        Me.[RELATIONSHIPSTARTDATE] = Me.HostModel.[RELATIONSHIPSTARTDATE]
        Me.[RELATIONSHIPENDDATE] = Me.HostModel.[RELATIONSHIPENDDATE]
        Me.[POSITION] = Me.HostModel.[POSITION]
        Me.[ISPRIMARYBUSINESS] = Me.HostModel.[ISPRIMARYBUSINESS]
        Me.[ISMATCHINGGIFTRELATIONSHIP] = Me.HostModel.[ISMATCHINGGIFTRELATIONSHIP]
        Me.[ADDADDRESS] = Me.HostModel.[ADDADDRESS]
        Me.[ADDRESSTYPECODEID] = Me.HostModel.[ADDRESSTYPECODEID]
        Me.[ADDRESSBLOCK] = Me.HostModel.[ADDRESSBLOCK]
        Me.[CITY] = Me.HostModel.[CITY]
        Me.[STATEID] = Me.HostModel.[STATEID]
        Me.[POSTCODE] = Me.HostModel.[POSTCODE]
        Me.[COUNTRYID] = Me.HostModel.[COUNTRYID]
        Me.[DONOTMAIL] = Me.HostModel.[DONOTMAIL]
        Me.[CART] = Me.HostModel.[CART]
        Me.[LOT] = Me.HostModel.[LOT]
        Me.[DPC] = Me.HostModel.[DPC]
        Me.[STARTDATE] = Me.HostModel.[STARTDATE]
        Me.[ENDDATE] = Me.HostModel.[ENDDATE]
        Me.[PRIMARY] = Me.HostModel.[PRIMARY]
        Me.[SPOUSENAME] = Me.HostModel.[SPOUSENAME]
        Me.[UPDATEMATCHINGSPOUSEADDRESSES] = Me.HostModel.[UPDATEMATCHINGSPOUSEADDRESSES]
        Me.[OMITFROMVALIDATION] = Me.HostModel.[OMITFROMVALIDATION]
        Me.[COUNTYCODEID] = Me.HostModel.[COUNTYCODEID]
        Me.[CONGRESSIONALDISTRICTCODEID] = Me.HostModel.[CONGRESSIONALDISTRICTCODEID]
        Me.[STATEHOUSEDISTRICTCODEID] = Me.HostModel.[STATEHOUSEDISTRICTCODEID]
        Me.[STATESENATEDISTRICTCODEID] = Me.HostModel.[STATESENATEDISTRICTCODEID]
        Me.[LOCALPRECINCTCODEID] = Me.HostModel.[LOCALPRECINCTCODEID]
        Me.[INFOSOURCECODEID] = Me.HostModel.[INFOSOURCECODEID]
        Me.[REGIONCODEID] = Me.HostModel.[REGIONCODEID]
        Me.[LASTVALIDATIONATTEMPTDATE] = Me.HostModel.[LASTVALIDATIONATTEMPTDATE]
        Me.[VALIDATIONMESSAGE] = Me.HostModel.[VALIDATIONMESSAGE]
        Me.[CERTIFICATIONDATA] = Me.HostModel.[CERTIFICATIONDATA]
        Me.[ZIPLOOKUPCOUNTRIES] = Me.HostModel.[ZIPLOOKUPCOUNTRIES]
        Me.[VALIDATIONCOUNTRIES] = Me.HostModel.[VALIDATIONCOUNTRIES]
        Me.[DONOTMAILREASONCODEID] = Me.HostModel.[DONOTMAILREASONCODEID]
        Me.[JOBCATEGORYCODEID] = Me.HostModel.[JOBCATEGORYCODEID]
        Me.[CAREERLEVELCODEID] = Me.HostModel.[CAREERLEVELCODEID]
        Me.[REPLACERELATIONSHIP] = Me.HostModel.[REPLACERELATIONSHIP]
        Me.[REPLACEMENTRELATIONSHIPID] = Me.HostModel.[REPLACEMENTRELATIONSHIPID]
        Me.[INFOSOURCECOMMENTS] = Me.HostModel.[INFOSOURCECOMMENTS]
        Me.[COMMENTS] = Me.HostModel.[COMMENTS]
        Me.[JOBSCHEDULECODEID] = Me.HostModel.[JOBSCHEDULECODEID]
        Me.[JOBDEPARTMENT] = Me.HostModel.[JOBDEPARTMENT]
        Me.[JOBDIVISION] = Me.HostModel.[JOBDIVISION]
        Me.[CONSTITUENTTYPE] = Me.HostModel.[CONSTITUENTTYPE]
        Me.[CONTACTADDRESSLABEL] = Me.HostModel.[CONTACTADDRESSLABEL]
        Me.[CONTACTADDRESS] = Me.HostModel.[CONTACTADDRESS]
        Me.[RELATIONSHIPGROUP] = Me.HostModel.[RELATIONSHIPGROUP]
        Me.[EMPLOYMENTINFOGROUP] = Me.HostModel.[EMPLOYMENTINFOGROUP]
        Me.[GENERALGROUP] = Me.HostModel.[GENERALGROUP]
        Me.[CONTACTGROUP] = Me.HostModel.[CONTACTGROUP]
        Me.[COMMENTSGROUP] = Me.HostModel.[COMMENTSGROUP]
        Me.[ADDADDRESSACTION] = Me.HostModel.[ADDADDRESSACTION]
        Me.[REMOVEADDRESSACTION] = Me.HostModel.[REMOVEADDRESSACTION]
        Me.[ADDNEWINDIVIDUAL] = Me.HostModel.[ADDNEWINDIVIDUAL]
        Me.[FORMHEADER] = Me.HostModel.[FORMHEADER]

        OnInit()

    End Sub

    Partial Private Sub OnInit()
    End Sub

End Class

