Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Food Bank Breakdown Report' data form
''' </summary>

Partial Public Class [FoodBankBreakdownReportUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.ReportParameterUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the DATETYPE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Enum DATETYPES As Integer
        [SpecificDate] = 0
        [AllDates] = 1
        [ThisYear] = 7
        [ThisFiscalYear] = 39
        [LastYear] = 13
        [LastFiscalYear] = 38
        [LastMonth] = 12
        [ThisMonth] = 6
        [LastQuarter] = 45
        [ThisQuarter] = 43
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _chosenitems As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportCHOSENITEMSUIModel)
    Private WithEvents _availableitems As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEITEMSUIModel)
    Private WithEvents _availabledata As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEDATAUIModel)
    Private WithEvents _group1 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _group2 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _group3 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data1 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data2 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data3 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data4 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data5 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data6 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data7 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _data8 As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _datetype As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _enddate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _allgroups As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
    Private WithEvents _alldata As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
    Private WithEvents _filteroptionstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _groupoptionstab As Global.Blackbaud.AppFx.UIModeling.Core.TabField
    Private WithEvents _additem As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _removeitem As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _moveitemup As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _moveitemdown As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _movedataup As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
    Private WithEvents _movedatadown As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public Sub New()
        MyBase.New()

        _chosenitems = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportCHOSENITEMSUIModel)
        _availableitems = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEITEMSUIModel)
        _availabledata = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEDATAUIModel)
        _group1 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _group2 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _group3 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data1 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data2 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data3 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data4 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data5 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data6 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data7 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _data8 = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _datetype = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _enddate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _allgroups = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
        _alldata = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
        _filteroptionstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _groupoptionstab = New Global.Blackbaud.AppFx.UIModeling.Core.TabField
        _additem = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _removeitem = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _moveitemup = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _moveitemdown = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _movedataup = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        _movedatadown = New Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction

        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/FoodBankBreakdownReport.html"

        '
        '_chosenitems
        '
        _chosenitems.Name = "CHOSENITEMS"
        _chosenitems.Caption = "Selected Groups"
        Me.Fields.Add(_chosenitems)
        '
        '_availableitems
        '
        _availableitems.Name = "AVAILABLEITEMS"
        _availableitems.Caption = "Available Groups"
        Me.Fields.Add(_availableitems)
        '
        '_availabledata
        '
        _availabledata.Name = "AVAILABLEDATA"
        _availabledata.Caption = "Available Data"
        Me.Fields.Add(_availabledata)
        '
        '_group1
        '
        _group1.Name = "GROUP1"
        _group1.Caption = "Group 1"
        _group1.Visible = False
        Me.Fields.Add(_group1)
        '
        '_group2
        '
        _group2.Name = "GROUP2"
        _group2.Caption = "Group 2"
        _group2.Visible = False
        Me.Fields.Add(_group2)
        '
        '_group3
        '
        _group3.Name = "GROUP3"
        _group3.Caption = "Group 3"
        _group3.Visible = False
        Me.Fields.Add(_group3)
        '
        '_data1
        '
        _data1.Name = "DATA1"
        _data1.Caption = "Data 1"
        _data1.Visible = False
        Me.Fields.Add(_data1)
        '
        '_data2
        '
        _data2.Name = "DATA2"
        _data2.Caption = "Data 2"
        _data2.Visible = False
        Me.Fields.Add(_data2)
        '
        '_data3
        '
        _data3.Name = "DATA3"
        _data3.Caption = "Data 3"
        _data3.Visible = False
        Me.Fields.Add(_data3)
        '
        '_data4
        '
        _data4.Name = "DATA4"
        _data4.Caption = "Data 4"
        _data4.Visible = False
        Me.Fields.Add(_data4)
        '
        '_data5
        '
        _data5.Name = "DATA5"
        _data5.Caption = "Data 5"
        _data5.Visible = False
        Me.Fields.Add(_data5)
        '
        '_data6
        '
        _data6.Name = "DATA6"
        _data6.Caption = "Data 6"
        _data6.Visible = False
        Me.Fields.Add(_data6)
        '
        '_data7
        '
        _data7.Name = "DATA7"
        _data7.Caption = "Data 7"
        _data7.Visible = False
        Me.Fields.Add(_data7)
        '
        '_data8
        '
        _data8.Name = "DATA8"
        _data8.Caption = "Data 8"
        _data8.Visible = False
        Me.Fields.Add(_data8)
        '
        '_datetype
        '
        _datetype.Name = "DATETYPE"
        _datetype.Caption = "Date Type"
        _datetype.Required = True
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[SpecificDate], .Translation = "Specific Date"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[AllDates], .Translation = "All Dates"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisYear], .Translation = "This Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisFiscalYear], .Translation = "This Fiscal Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastYear], .Translation = "Last Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastFiscalYear], .Translation = "Last Fiscal Year"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastMonth], .Translation = "Last Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisMonth], .Translation = "This Month"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[LastQuarter], .Translation = "Last Quarter"})
        _datetype.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of DATETYPES) With {.Value = DATETYPES.[ThisQuarter], .Translation = "This Quarter"})
        _datetype.Value = DATETYPES.[AllDates]
        Me.Fields.Add(_datetype)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "From"
        Me.Fields.Add(_startdate)
        '
        '_enddate
        '
        _enddate.Name = "ENDDATE"
        _enddate.Caption = "To"
        Me.Fields.Add(_enddate)
        '
        '_allgroups
        '
        _allgroups.Name = "ALLGROUPS"
        _allgroups.Caption = "All Groups"
        _allgroups.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "FOODBANKTYPE", .Translation = "Food Bank Type"})
        _allgroups.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "FOODITEM", .Translation = "Food Item"})
        _allgroups.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "COUNTRY", .Translation = "Country"})
        _allgroups.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "STATE", .Translation = "State"})
        _allgroups.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "CITY", .Translation = "City"})
        Me.Fields.Add(_allgroups)
        '
        '_alldata
        '
        _alldata.Name = "ALLDATA"
        _alldata.Caption = "All Data Options"
        _alldata.Visible = False
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALAMOUNTDISTRIBUTED", .Translation = "Total Amount Distributed"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALAMOUNTRECEIVED", .Translation = "Total Amount Received"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALQUANTITYDISTRIBUTED", .Translation = "Total Quantity Distributed"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALQUANTITYRECEIVED", .Translation = "Total Quantity Received"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALPOUNDSDISTRIBUTED", .Translation = "Total Pounds Distributed"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TOTALPOUNDSRECEIVED", .Translation = "Total Pounds Received"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "FOODBANKCOUNT", .Translation = "Food Bank Count"})
        _alldata.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of String) With {.Value = "TRANSACTIONCOUNT", .Translation = "Transaction Count"})
        Me.Fields.Add(_alldata)
        '
        '_filteroptionstab
        '
        _filteroptionstab.Name = "FILTEROPTIONSTAB"
        _filteroptionstab.Caption = "Filters"
        Me.Fields.Add(_filteroptionstab)
        '
        '_groupoptionstab
        '
        _groupoptionstab.Name = "GROUPOPTIONSTAB"
        _groupoptionstab.Caption = "Layout"
        Me.Fields.Add(_groupoptionstab)
        '
        '_additem
        '
        _additem.Name = "ADDITEM"
        _additem.Caption = "Add item"
        Me.Actions.Add(_additem)
        '
        '_removeitem
        '
        _removeitem.Name = "REMOVEITEM"
        _removeitem.Caption = "Remove item"
        Me.Actions.Add(_removeitem)
        '
        '_moveitemup
        '
        _moveitemup.Name = "MOVEITEMUP"
        _moveitemup.Caption = "Move item up"
        Me.Actions.Add(_moveitemup)
        '
        '_moveitemdown
        '
        _moveitemdown.Name = "MOVEITEMDOWN"
        _moveitemdown.Caption = "Move item down"
        Me.Actions.Add(_moveitemdown)
        '
        '_movedataup
        '
        _movedataup.Name = "MOVEDATAUP"
        _movedataup.Caption = "Move data up"
        Me.Actions.Add(_movedataup)
        '
        '_movedatadown
        '
        _movedatadown.Name = "MOVEDATADOWN"
        _movedatadown.Caption = "Move data down"
        Me.Actions.Add(_movedatadown)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Selected Groups
    ''' </summary>
    <System.ComponentModel.Description("Selected Groups")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [CHOSENITEMS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportCHOSENITEMSUIModel)
        Get
            Return _chosenitems
        End Get
    End Property
    
    ''' <summary>
    ''' Available Groups
    ''' </summary>
    <System.ComponentModel.Description("Available Groups")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [AVAILABLEITEMS]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEITEMSUIModel)
        Get
            Return _availableitems
        End Get
    End Property
    
    ''' <summary>
    ''' Available Data
    ''' </summary>
    <System.ComponentModel.Description("Available Data")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [AVAILABLEDATA]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of FoodBankBreakdownReportAVAILABLEDATAUIModel)
        Get
            Return _availabledata
        End Get
    End Property
    
    ''' <summary>
    ''' Group 1
    ''' </summary>
    <System.ComponentModel.Description("Group 1")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [GROUP1]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _group1
        End Get
    End Property
    
    ''' <summary>
    ''' Group 2
    ''' </summary>
    <System.ComponentModel.Description("Group 2")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [GROUP2]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _group2
        End Get
    End Property
    
    ''' <summary>
    ''' Group 3
    ''' </summary>
    <System.ComponentModel.Description("Group 3")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [GROUP3]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _group3
        End Get
    End Property
    
    ''' <summary>
    ''' Data 1
    ''' </summary>
    <System.ComponentModel.Description("Data 1")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA1]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data1
        End Get
    End Property
    
    ''' <summary>
    ''' Data 2
    ''' </summary>
    <System.ComponentModel.Description("Data 2")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA2]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data2
        End Get
    End Property
    
    ''' <summary>
    ''' Data 3
    ''' </summary>
    <System.ComponentModel.Description("Data 3")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA3]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data3
        End Get
    End Property
    
    ''' <summary>
    ''' Data 4
    ''' </summary>
    <System.ComponentModel.Description("Data 4")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA4]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data4
        End Get
    End Property
    
    ''' <summary>
    ''' Data 5
    ''' </summary>
    <System.ComponentModel.Description("Data 5")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA5]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data5
        End Get
    End Property
    
    ''' <summary>
    ''' Data 6
    ''' </summary>
    <System.ComponentModel.Description("Data 6")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA6]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data6
        End Get
    End Property
    
    ''' <summary>
    ''' Data 7
    ''' </summary>
    <System.ComponentModel.Description("Data 7")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA7]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data7
        End Get
    End Property
    
    ''' <summary>
    ''' Data 8
    ''' </summary>
    <System.ComponentModel.Description("Data 8")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATA8]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _data8
        End Get
    End Property
    
    ''' <summary>
    ''' Date Type
    ''' </summary>
    <System.ComponentModel.Description("Date Type")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [DATETYPE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of DATETYPES)
        Get
            Return _datetype
        End Get
    End Property
    
    ''' <summary>
    ''' From
    ''' </summary>
    <System.ComponentModel.Description("From")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' To
    ''' </summary>
    <System.ComponentModel.Description("To")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ENDDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _enddate
        End Get
    End Property
    
    ''' <summary>
    ''' All Groups
    ''' </summary>
    <System.ComponentModel.Description("All Groups")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ALLGROUPS]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
        Get
            Return _allgroups
        End Get
    End Property
    
    ''' <summary>
    ''' All Data Options
    ''' </summary>
    <System.ComponentModel.Description("All Data Options")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ALLDATA]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of String)
        Get
            Return _alldata
        End Get
    End Property
    
    ''' <summary>
    ''' Filters
    ''' </summary>
    <System.ComponentModel.Description("Filters")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [FILTEROPTIONSTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _filteroptionstab
        End Get
    End Property
    
    ''' <summary>
    ''' Layout
    ''' </summary>
    <System.ComponentModel.Description("Layout")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [GROUPOPTIONSTAB]() As Global.Blackbaud.AppFx.UIModeling.Core.TabField
        Get
            Return _groupoptionstab
        End Get
    End Property
    
    ''' <summary>
    ''' Add item
    ''' </summary>
    <System.ComponentModel.Description("Add item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [ADDITEM]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _additem
        End Get
    End Property
    
    ''' <summary>
    ''' Remove item
    ''' </summary>
    <System.ComponentModel.Description("Remove item")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [REMOVEITEM]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _removeitem
        End Get
    End Property
    
    ''' <summary>
    ''' Move item up
    ''' </summary>
    <System.ComponentModel.Description("Move item up")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [MOVEITEMUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _moveitemup
        End Get
    End Property
    
    ''' <summary>
    ''' Move item down
    ''' </summary>
    <System.ComponentModel.Description("Move item down")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [MOVEITEMDOWN]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _moveitemdown
        End Get
    End Property
    
    ''' <summary>
    ''' Move data up
    ''' </summary>
    <System.ComponentModel.Description("Move data up")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [MOVEDATAUP]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _movedataup
        End Get
    End Property
    
    ''' <summary>
    ''' Move data down
    ''' </summary>
    <System.ComponentModel.Description("Move data down")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "1.0.0.0")> _
    Public ReadOnly Property [MOVEDATADOWN]() As Global.Blackbaud.AppFx.UIModeling.Core.GenericUIAction
        Get
            Return _movedatadown
        End Get
    End Property
    
End Class
