Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Top Food Item Shortages By BPRun Data List' data form
''' </summary>
<Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("772f60b1-9f96-4f34-ba94-a5a4f1a81180")> _
Partial Public Class [TopFoodItemShortagesByBPRunDataListUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _businessprocessoutputid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _sumcurrentinvertorysoldout As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _businessprocessoutputid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _sumcurrentinvertorysoldout = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField

        MyBase.DataListId = New Guid("772f60b1-9f96-4f34-ba94-a5a4f1a81180")
        MyBase.UserInterfaceUrl = "browser/htmlforms/custom/blackbaud.customfx.foodbank/TopFoodItemShortagesByBPRunDataList.html"

        '
        '_businessprocessoutputid
        '
        _businessprocessoutputid.Name = "BUSINESSPROCESSOUTPUTID"
        _businessprocessoutputid.Caption = "Low Inventory Snapshot"
        _businessprocessoutputid.SimpleDataListID = New Guid("5710af5e-2cef-4014-a9b4-eec1f246b582")
        _businessprocessoutputid.BlankValueCaption = "Select a Business Process Run"
        Me.Fields.Add(_businessprocessoutputid)
        '
        '_sumcurrentinvertorysoldout
        '
        _sumcurrentinvertorysoldout.Name = "SUMCURRENTINVERTORYSOLDOUT"
        _sumcurrentinvertorysoldout.Caption = "Sold Out"
        Me.Fields.Add(_sumcurrentinvertorysoldout)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Low Inventory Snapshot
    ''' </summary>
    <System.ComponentModel.Description("Low Inventory Snapshot")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BUSINESSPROCESSOUTPUTID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _businessprocessoutputid
        End Get
    End Property
    
    ''' <summary>
    ''' Sold Out
    ''' </summary>
    <System.ComponentModel.Description("Sold Out")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [SUMCURRENTINVERTORYSOLDOUT]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _sumcurrentinvertorysoldout
        End Get
    End Property
    
End Class
